development:
  secret_key_base: <%= PRIVATE['secure']['key_base'] %>

test:
  secret_key_base: <%= PRIVATE['secure']['key_base'] %>

production:
  secret_key_base: <%= PRIVATE['secure']['key_base'] %>
